
const ANIMATION_DURATION = 1;
const OFFSET_DISTANCE = 5;

const SCALE_LARGE_DESKTOP = 0.08;
const SCALE_LARGE_MOBILE = 0.05;

export {
    ANIMATION_DURATION,
    OFFSET_DISTANCE,
    SCALE_LARGE_DESKTOP,
    SCALE_LARGE_MOBILE
}